export const VOICE_RECOGNITION_MAPPINGS = {
  // Offices
  'osa': 'OFFICE_OF_STUDENT_AFFAIRS',
  'office of student affairs': 'OFFICE_OF_STUDENT_AFFAIRS',
  'student affairs': 'OFFICE_OF_STUDENT_AFFAIRS',
  'student affairs office': 'OFFICE_OF_STUDENT_AFFAIRS',
  'dean': 'DEANS_OFFICE',
  'dean office': 'DEANS_OFFICE',
  'dean\'s office': 'DEANS_OFFICE',
  'guidance': 'GUIDANCE_OFFICE',
  'guidance office': 'GUIDANCE_OFFICE',
  'guidance counselor': 'GUIDANCE_OFFICE',
  'guidance counselor office': 'GUIDANCE_OFFICE',
  'testing': 'TESTING1',
  'testing1': 'TESTING1',
  'testing2': 'TESTING2',
  'lazaro': 'LAZARO_HALL',
  'lazaro hall': 'LAZARO_HALL',
  'nurse': 'NURSE_OFFICE',
  'nurse office': 'NURSE_OFFICE',
  'nurse\'s office': 'NURSE_OFFICE',
  'president': 'PRESIDENTS_OFFICE',
  'president\'s office': 'PRESIDENTS_OFFICE',
  'president\'s office': 'PRESIDENTS_OFFICE',
  'hr': 'HR_OFFICE',
  'hr office': 'HR_OFFICE',
  'hr\'s office': 'HR_OFFICE',
  'conference': 'CONFERENCE_ROOM',
  'conference room': 'CONFERENCE_ROOM',
  'conference room': 'CONFERENCE_ROOM',
  'supreme student council': 'SUPREME_STUDENT_COUNCIL',
  'supreme student council room': 'SUPREME_STUDENT_COUNCIL',
  'ssc': 'SUPREME_STUDENT_COUNCIL',
  'ssc room': 'SUPREME_STUDENT_COUNCIL',
  
  // Common areas
  'cr': 'CR',
  'comfort room': 'CR',
  'bathroom': 'CR',
  'restroom': 'CR',
  'washroom': 'CR',
  
  // Admin offices
  'registrar': 'REGISTRAR',
  'registrars office': 'REGISTRAR',
  'registration': 'REGISTRAR',
  
  'cashier': 'CASHIER',
  'cashiers office': 'CASHIER',
  'payment': 'CASHIER',
  'where to pay': 'CASHIER',
  'bayad': 'CASHIER',
  
  // Academic spaces
  'faculty': 'FACULTY_ROOM',
  'faculty room': 'FACULTY_ROOM',
  'teachers room': 'FACULTY_ROOM',
  'professors room': 'FACULTY_ROOM',
  'guro': 'FACULTY_ROOM',
  'teacher': 'FACULTY_ROOM',
  
  // Labs
  'physics': 'PHYSICS_LAB',
  'physics laboratory': 'PHYSICS_LAB',
  'physics lab': 'PHYSICS_LAB',
  'science': 'PHYSICS_LAB',
  
  'bio lab': 'BIOLOGY_LAB',
  'biology': 'BIOLOGY_LAB',
  'biology laboratory': 'BIOLOGY_LAB',
  'lab': 'BIOLOGY_LAB',

  // MISD
  'misd': 'MISD',
  'mist': 'MISD',
  'm i s d': 'MISD',
  'em i s d': 'MISD',
  'm.i.s.d': 'MISD',
  'management information system': 'MISD',
  'mis': 'MISD',
  'misd office': 'MISD',

  // Other offices
  'alumni': 'alumni',
  'alumni office': 'alumni',
  'socios': 'socios',
  'socios office': 'socios',
  'storage': 'storage',
  'storage room': 'storage',
  'sports': 'sports',
  'sports room': 'sports',
  'canteen': 'canteen',
  'canteen room': 'canteen',
  'kainan': 'canteen',
  'pagkainan': 'canteen',
  'tindahan': 'canteen',

  // AB Rooms
  'ab2': 'AB2',
  'ab2 room': 'AB2',
  'ab too': 'AB2',
  'ab3': 'AB3',
  'ab3 room': 'AB3',
  'ab tree': 'AB3',
  'ab4': 'AB4',
  'ab4 room': 'AB4',
    'ab four': 'AB4',
  'ab for': 'AB4',
  'ab5': 'AB5',
  'ab5 room': 'AB5',
  'ab6': 'AB6',
  'ab6 room': 'AB6',
  'ab7': 'AB7',
  'ab7 room': 'AB7',
  'ab8': 'AB8',
  'ab8 room': 'AB8',
  'ab9': 'AB9',
  'ab9 room': 'AB9',

  // AV Room
  'av': 'AV_ROOM',
  'av room': 'AV_ROOM',

  // JMC Rooms
  '1jmc-cl1': 'JMC_CL1',
  '1 gmc cl1': 'JMC_CL1',
  'one j m c cl one': 'JMC_CL1',  
  '1jmc-cl1 room': 'JMC_CL1',
  '1jmc-cl1': 'JMC_CL1',
  '1jmc-cl2': 'JMC_CL2',
  '1 gmc cl2': 'JMC_CL2',
  'one j m c cl two': 'JMC_CL2',
  '1jmc-cl2 room': 'JMC_CL2',
  '1jmc-cl2': 'JMC_CL2',
  '1jmc-cl3': 'JMC_CL3',
  '1 gmc cl3': 'JMC_CL3',
  'one j m c cl three': 'JMC_CL3',
  '1jmc-cl3 room': 'JMC_CL3',
  '1jmc-cl3': 'JMC_CL3',
  '1jmc-cl4': 'JMC_CL4',
  '1 gmc cl4': 'JMC_CL4',
  'one j m c cl four': 'JMC_CL4',
  '1jmc-cl4 room': 'JMC_CL4',
  '1jmc-cl4': 'JMC_CL4',
  '1jmc-cl5': 'JMC_CL5',
  '1 gmc cl5': 'JMC_CL5',
  'one j m c cl five': 'JMC_CL5',
  '1jmc-cl5 room': 'JMC_CL5',
  '1jmc-cl5': 'JMC_CL5',
  '1jmc-ca': 'JMC_CA',
  '1 gmc ca': 'JMC_CA',
  'one j m c ca': 'JMC_CA',
  '1jmc-ca room': 'JMC_CA',
  '1jmc-ca': 'JMC_CA',
  '2jmc3': 'JMC3',
  '2 gmc 3': 'JMC3',
  '2jmc 3': 'JMC3',
  'two j m c three': 'JMC3',
  'two jmc three': 'JMC3',
  '2 j m c 3': 'JMC3',
  '2 jmc 3': 'JMC3',
  'second floor jmc 3': 'JMC3',
  'second floor j m c 3': 'JMC3',
  '2jmc4': 'JMC4',
  '2 gmc 4': 'JMC4',
  '2jmc 4': 'JMC4',
  'two j m c four': 'JMC4',
  'two jmc four': 'JMC4',
  '2 j m c 4': 'JMC4',
  '2 jmc 4': 'JMC4',
  'second floor jmc 4': 'JMC4',
  'second floor j m c 4': 'JMC4',
  '2jmc5': 'JMC5',
  '2 gmc 5': 'JMC5',
  '2jmc 5': 'JMC5',
  'two j m c five': 'JMC5',
  'two jmc five': 'JMC5',
  '2 j m c 5': 'JMC5',
  '2 jmc 5': 'JMC5',
  'second floor jmc 5': 'JMC5',
  'second floor j m c 5': 'JMC5',
  '2jmc6': 'JMC6',
  '2 gmc 6': 'JMC6',
  '2jmc 6': 'JMC6',
  'two j m c six': 'JMC6',
  'two jmc six': 'JMC6',
  '2 j m c 6': 'JMC6',
  '2 jmc 6': 'JMC6',
  'second floor jmc 6': 'JMC6',
  'second floor j m c 6': 'JMC6',
  '3jmc7': 'JMC7',
  '3 gmc 7': 'JMC7',
  '3jmc 7': 'JMC7',
  'three j m c seven': 'JMC7',
  '3 j m c 7': 'JMC7',
  '3jmc8': 'JMC8',
  '3 gmc 8': 'JMC8',
  '3jmc 8': 'JMC8',
  'three j m c eight': 'JMC8',
  '3 j m c 8': 'JMC8',
  '3jmc9': 'JMC9',
  '3 gmc 9': 'JMC9',
  '3jmc 9': 'JMC9',
  'three j m c nine': 'JMC9',
  '3 j m c 9': 'JMC9',
  '3jmc10': 'JMC10',
  '3 gmc 10': 'JMC10',
  '3jmc 10': 'JMC10',
  'three j m c ten': 'JMC10',
  '3 j m c 10': 'JMC10',
  '3jmc11': 'JMC11',
  '3 gmc 11': 'JMC11',
  '3jmc 11': 'JMC11',
  'three j m c eleven': 'JMC11',
  '3 j m c 11': 'JMC11',
  '3jmc 12': 'JMC12',
  '3 gmc 12': 'JMC12',
  '3jmc 12': 'JMC12',
  'three j m c twelve': 'JMC12',
  '3 j m c 12': 'JMC12',

  // Library & OCL
  'ocl': 'OFFICE_OF_THE_CHIEF_LIBRARIAN',
  'office of the chief librarian': 'OFFICE_OF_THE_CHIEF_LIBRARIAN',
  'ocl room': 'OFFICE_OF_THE_CHIEF_LIBRARIAN',
  'library': 'LIBRARY',
  'library room': 'LIBRARY',

  // Rizal Building Rooms
  'r1': 'R1',
  'r one': 'R1',
  'r1 room': 'R1',
  'rizal1': 'R1',
  'rizal 1 ': 'R1',
  'r2': 'R2',
  'r two': 'R2',
  'r2 room': 'R2',
  'rizal2': 'R2',
  'rizal 2 ': 'R2',
  'r3': 'R3',
  'r three': 'R3',
  'r3 room': 'R3',
  'rizal3': 'R3',
  'rizal 3 ': 'R3',
  'r4': 'R4',
  'r four': 'R4',
  'r4 room': 'R4',
  'rizal4': 'R4',
  'rizal 4 ': 'R4',
  'r5': 'R5',
  'r five': 'R5',
  'r5 room': 'R5',
  'rizal5': 'R5',
  'rizal 5 ': 'R5',
  'r6': 'R6',
  'r six': 'R6',
  'r6 room': 'R6',
  'rizal6': 'R6',
  'rizal 6 ': 'R6',
  'r7': 'R7',
  'r seven': 'R7',
  'r7 room': 'R7',
  'rizal7': 'R7',
  'rizal 7 ': 'R7',
  'r8': 'R8',
  'r eight': 'R8',
  'r8 room': 'R8',
  'rizal8': 'R8',
  'rizal 8 ': 'R8',
  'r9': 'R9',
  'r nine': 'R9',
  'r9 room': 'R9',
  'rizal9': 'R9',
  'rizal 9 ': 'R9',
  'r10': 'R10',
  'r ten': 'R10',
  'r10 room': 'R10',
  'rizal10': 'R10',
  'rizal 10 ': 'R10',
  'r11': 'R11',
  'r eleven': 'R11',
  'r11 room': 'R11',
  'rizal11': 'R11',
  'rizal 11 ': 'R11',
  'r12': 'R12',
  'r twelve': 'R12',
  'r12 room': 'R12',
  'rizal12': 'R12',
  'rizal 12 ': 'R12',
  'r13': 'R13',
  'r thirteen': 'R13',
  'r13 room': 'R13',
  'rizal13': 'R13',
  'rizal 13 ': 'R13',
  'r14': 'R14',
  'r fourteen': 'R14',
  'r14 room': 'R14',
  'rizal14': 'R14',
  'rizal 14 ': 'R14',
}; 